### ISSUE TITLE
Level One

### ISSUE THREAD

**Issue by camerongough** [HolmesSquad/Project-Three#1]
The program should allow the user to select and place different 
types of treasures (e.g. jewellery, coins, silverware) within an 
arena and assign each treasure with a score. With a starting point 
and time also provided by the user, a robot should start with the 
nearest treasure and gather as many treasures as possible within 
the given time. 
The robot will then sort and display the treasures that have been 
collected according to some criteria defined by the user (e.g. an 
ascending or descending order of scores).

**Comment by AlexHodson** [comment]
only thing left to do on level 1 is extend the coordinates list for moving the treasure into the inventory to 15 not 10

**Comment by AlexHodson** [comment]
Everything is done we believe
