### ISSUE TITLE
Treasure information

### ISSUE THREAD

**Issue by Holmest5** [HolmesSquad/Project-Three#8]

**Comment by Ashti** [comment]
Done a prototype version. It isn't in OOP format but i will adjust it when the level code and robot code is ready.

**Comment by Ashti** [comment]
Label Code Prototype has been made into a roll over which isn't completed yet.

**Comment by Ashti** [comment]
Got a rollover effect to work. Isn't really complex and would be hard to adjust to a class though. I will adjust it into the program when there is a treasure class.

**Comment by Ashti** [comment]
It has been fixed and now works. So this issue is closed.
